# Fly.io Deployment Configuration for FlowLogic RouteAI
# Deploy with: fly deploy

app = "flowlogic-routeai"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[build]
  dockerfile = "docker/Dockerfile.api"

[env]
  ENVIRONMENT = "production"
  # Database and Redis URLs will be set via secrets
  # Sensitive vars should be set with: fly secrets set KEY=value

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"

[mounts]
  source = "flowlogic_data"
  destination = "/app/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    port = 8000
    timeout = "5s"

[[services]]
  internal_port = 8001
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 8001

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    port = 8001
    timeout = "5s"

# Resource allocation
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Scaling configuration
[metrics]
  port = 9091
  path = "/metrics"

[[deploy.strategies]]
  [deploy.strategy]
  rolling = "immediate"